
[timers]
	"king's_scent_timer" = true
	reheated_gummy_bear_timer = true
	phoenix_rekindle_cd_timer = true
	mushy_tonic_timer = true
	spirit_mask_cd_timer = true
	flux_countdown_timer = true

[debug]
	debug_mode = false

[dungeons]
	"toggle:_player_actions" = false
	"toggle:_system_notifications" = false
	"toggle:_interactive_elements" = false
	full_inventory_alert = false
	"toggle:_qol" = false
	party_finder_message_shortener = false
	melody_terminal_alert = false
	better_dungeon_messages = false
	bonzo_mask_cd_timer = false

	[dungeons.secrets]
		"display_secrets_per_run_(per_session)" = false

[sound]
	rng_sounds = 0

[fishing_qol]
	full_thunder_bottle_ping = true

	[fishing_qol.message_hiders]
		hide_sc_messages = true
		hide_blessing_enchant_messages = true
		hide_double_hook_messages = true

	[fishing_qol.timers]
		phoenix_rekindle_cd_timer = true
		mushy_tonic_timer = true
		spirit_mask_cd_timer = true

[counter]
	"counter:_drops" = true
	fishing_counter = true
	"counter:_time_elapsed_since_[rng]" = true
	"counter:_kills" = true
	"counter:_special_funny_counters" = true
	"counter:_mob_since_[rng]" = true
	"counter:_trackers" = true
	"counter:_averages" = true

[general_qol]

	[general_qol.messages_qol]
		hide_autopet_messages = true
		removed_watchdog_announcements = true
		hide_soopy_unknown_command_message = true
		grandma_hider = true
		"hide_aote/aotv_message" = true
		hide_snow_cannon_messages = true
		better_stash_messages = true
		hide_click_stash_messages = true
		hide_lightning = true

	[general_qol.commands]
		auto_warp_command = true
		warpexc_command = true
		auto_notify_new_party_joiners = true
		party_kickoffline_shortcut = true
		party_allinvite_shortcut = true

	[general_qol.qol]
		easy_get_baker_cake = true
		kicked_notifier = true
		boop_notifier = true

[hp_display]

	[hp_display.toggleables]
		"display_hp:_phantom_fishers" = true
		mob_hp_display_master_toggle = true
		"display_hp:_vanquishers" = true
		"display_hp:_yeti" = true
		"display_hp:_mythos_mobs" = true
		"display_hp:_grim_reapers" = true
		"display_hp:_jawbus" = true
		"display_hp:_water_hydras" = true
		"display_hp:_inquisitors" = true
		"display_hp:_sea_emperors" = true
		"display_hp:_reindrakes" = true
		"display_hp:_great_whites" = true
		"display_hp:_thunder" = true
		"display_hp:_carrot_kings" = true
		"display_hp:_champions" = true

[gui]
	bobber_count = true
	detect_double_jawbus = true
	players_nearby_count = true
	detect_charge_counter = true
	detect_double_thunder = true

	[gui.toggles]
		bobber_count = false
		detect_double_jawbus = false
		players_nearby_count = false
		detect_charge_counter = false
		detect_double_thunder = false

[garden]
	garden_pet_drop_pings = false
	garden_rare_drop_pings = false

	[garden.overlays]
		vinyl_display = false
		pest_repellent_timer = false
		display_contest_overlay = false
		harbringer_potion_timer = false
		player_yaw_and_pitch = false
		pest_exchange_timer = false
		sprayonator_display = false

	[garden.qol]
		plot_map = false
		pest_qol = false
		sprayonator_no_mat_alert = false
		hide_sprayonator_expiry_message = false
		screen_pest_alert = false
		sprayonator_selected_mat_message_hider = false
		autowarp_pest = false
		pest_esp = false
		better_garden_messages = false
		auto_set_home_pest = false

[mythos]

	[mythos.counter]
		mythos_counter = false
		mythos_mob_averages_info = false
		mythos_mob_trackers_info = false
		general_mythos_info = false
		mythos_mob_drops_info = false
		mythos_mob_kills_info = false

	[mythos.qol]
		announce_inqs = false
		hide_leg_griffin_error = false

[fishing_pings]

	[fishing_pings.crimson_isles]
		vanquisher_ping = true
		radioactive_vial_ping = true
		phlegblast_ping = true
		jawbus_ping = true
		thunder_ping = true

	[fishing_pings.hub_shark]
		meg_pet_drop_ping = true
		great_white_shark_ping = true

	[fishing_pings.hub]
		sea_emperor_ping = true
		squid_pet_drop_ping = true
		dolphin_milestone_pet_drop_ping = true
		carrot_king_ping = true
		lucky_clover_core_ping = true
		water_hydra_ping = true
		guardian_pet_drop_ping = true
		flying_fish_pet_drop_ping = true

	[fishing_pings.winter_island]
		nutcracker_ping = true
		baby_yeti_pet_drop_ping = true
		reindrake_ping = true
		yeti_ping = true

	[fishing_pings.zothers]
		zombie_miner_ping = true
		fawe_default_pings = true

	[fishing_pings.hub_spooky]
		grim_reaper_ping = true
		phantom_fisher_ping = true
		deep_sea_orb_ping = true
		phantom_rod_ping = true
		lucky_hoof_ping = true

[dragons]

	[dragons.counter]
		"drag_counter:_trackers" = false
		dragon_counter = false
		"drag_counter:_spawns" = false

	[dragons.qol]
		alert_special_zealot = false
		better_end_messages = false

[misc]
	mute_the_sheep = false

	[misc.spooky]
		trick_or_treat_mobs_ping = false
		primal_fear_ping = false
		hide_fear_messages = false
		primal_fear_main_toggle = false
		headless_horseman_ping = false
		solver_for_karen_fear = false
		solver_for_mathematician_fear = false

	[misc.end]
		end_protector_ping = false

	[misc.mining]
		lobby_day_counter = false
		scatha_pet_drop_alert = false
		golden_goblin_alert = false

	[misc.jerry]
		hidden_jerry_ping = false

	[misc.dyes]
		dye_pings = false
		announce_dye_pings_in_guild = false

