
[timers]
	"king's_scent_timer" = false
	reheated_gummy_bear_timer = false
	phoenix_rekindle_cd_timer = false
	mushy_tonic_timer = false
	spirit_mask_cd_timer = false
	flux_countdown_timer = false

[debug]
	debug_mode = false

[ping]
	ping_display = false
	tps_display = false

	[ping.commands]
		ping_command = false

[dungeons]
	"toggle:_player_actions" = false
	class_specific_pings = false
	full_inventory_alert = false
	"toggle:_qol" = false
	"class/cata_lvl_up_ping" = false
	melody_terminal_alert = false
	better_dungeon_messages = false
	display_dungeon_blessings = false
	join_dungeon_shortcuts = false
	"toggle:_system_notifications" = false
	"toggle:_interactive_elements" = false
	party_finder_message_shortener = false
	fire_freeze_timers = false
	bonzo_mask_cd_timer = false

	[dungeons.secrets]
		"display_secrets_per_run_(per_session)" = false

[sound]
	rng_sounds = 0

["dragons/end"]
	dragon_hitbox = false

	["dragons/end".counter]
		"drag_counter:_trackers" = true
		dragon_counter = true
		dragon_damage_display = true
		"drag_counter:_spawns" = true

	["dragons/end".qol]
		alert_special_zealot = true
		end_protector_ping = true
		better_end_messages = true

[fishing_qol]
	full_thunder_bottle_ping = false

	[fishing_qol.message_hiders]
		hide_sc_messages = false
		hide_blessing_enchant_messages = true
		hide_double_hook_messages = true
		better_fishing_messages = false

	[fishing_qol.timers]
		phoenix_rekindle_cd_timer = true
		mushy_tonic_timer = true
		spirit_mask_cd_timer = true

[counter]
	"counter:_drops" = true
	fishing_counter = true
	"counter:_time_elapsed_since_[rng]" = true
	"counter:_kills" = true
	"counter:_special_funny_counters" = true
	"counter:_mob_since_[rng]" = true
	"counter:_trackers" = true
	"counter:_averages" = true

	[counter.overlay]
		"counter:_drops" = false
		fishing_counter = false
		"counter:_time_elapsed_since_[rng]" = false
		"counter:_kills" = false
		"counter:_special_funny_counters" = false
		"counter:_mob_since_[rng]" = false
		"counter:_trackers" = false
		"counter:_averages" = false

[general_qol]

	[general_qol.messages_qol]
		hide_autopet_messages = false
		removed_watchdog_announcements = false
		hide_soopy_unknown_command_message = true
		grandma_hider = false
		"hide_aote/aotv_message" = false
		hide_snow_cannon_messages = false
		better_stash_messages = false
		hide_click_stash_messages = false
		hide_lightning = false

	[general_qol.commands]
		party_transfer_randomly = false
		tps_command = false
		auto_warp_command = false
		warpexc_command = false
		ping_command = false
		auto_notify_new_party_joiners = false
		party_kickoffline_shortcut = false
		party_allinvite_shortcut = false

	[general_qol.qol]
		easy_get_baker_cake = false
		kicked_notifier = false
		boop_notifier = true

[hp_display]
	"display_hp:_phantom_fishers" = false
	mob_hp_display_master_toggle = false
	"display_hp:_vanquishers" = false
	"display_hp:_yeti" = false
	"display_hp:_mythos_mobs" = false
	"display_hp:_grim_reapers" = false
	"display_hp:_jawbus" = false
	"display_hp:_water_hydras" = false
	"display_hp:_inquisitors" = false
	"display_hp:_sea_emperors" = false
	"display_hp:_reindrakes" = false
	"display_hp:_great_whites" = false
	"display_hp:_thunder" = false
	"display_hp:_carrot_kings" = false
	"display_hp:_champions" = false

	[hp_display.toggleables]
		"display_hp:_phantom_fishers" = true
		mob_hp_display_master_toggle = false
		"display_hp:_vanquishers" = true
		"display_hp:_yeti" = true
		"display_hp:_mythos_mobs" = true
		"display_hp:_grim_reapers" = true
		"display_hp:_jawbus" = true
		"display_hp:_water_hydras" = true
		"display_hp:_inquisitors" = true
		"display_hp:_sea_emperors" = true
		"display_hp:_reindrakes" = true
		"display_hp:_great_whites" = true
		"display_hp:_thunder" = true
		"display_hp:_carrot_kings" = true
		"display_hp:_champions" = true

["dragons/end/end"]

	["dragons/end/end".qol]
		end_protector_ping = false

[tps]
	tps_display = false

	[tps.commands]
		tps_command = false

[gui]
	bobber_count = false
	detect_double_jawbus = true
	lobby_day_counter = false
	players_nearby_count = false
	ping_display = false
	detect_charge_counter = false
	nearby_thunder_count = false
	detect_double_thunder = true
	nearby_jawbus_count = false
	tps_display = false

	[gui.toggles]
		bobber_count = false
		detect_double_jawbus = false
		players_nearby_count = false
		detect_charge_counter = false
		detect_double_thunder = false

[garden]
	garden_pet_drop_pings = false
	garden_rare_drop_pings = false

	[garden.pest_qol]
		pest_qol = false
		"pest_qol:_screen_pest_alert" = false
		"pest_qol:_auto_set_home_pest" = false
		"pest_qol:_esp" = false
		"pest_qol:_autowarp_pest" = false

	[garden.timers]
		pest_repellent_timer = false
		harbringer_potion_timer = false
		pest_exchange_timer = false

	[garden.overlays]
		vinyl_display = false
		pest_repellent_timer = true
		display_contest_overlay = false
		harbringer_potion_timer = true
		player_yaw_and_pitch = false
		pest_exchange_timer = true
		sprayonator_display = false

	[garden.qol]
		plot_map = false
		pest_qol = true
		sprayonator_no_mat_alert = false
		"pest_qol:_screen_pest_alert" = true
		"pest_qol:_auto_set_home_pest" = true
		"pest_qol:_esp" = true
		"pest_qol:_autowarp_pest" = true
		auto_set_home_pest = true
		hide_sprayonator_expiry_message = false
		screen_pest_alert = true
		sprayonator_selected_mat_message_hider = false
		autowarp_pest = true
		pest_esp = true
		better_garden_messages = false

["sounds/dev"]

	["sounds/dev".debug]
		debug_mode = false

	["sounds/dev".sounds]
		rng_sounds = 0

[mythos]

	[mythos.counter]
		mythos_counter = false
		mythos_mob_averages_info = false
		mythos_mob_trackers_info = false
		general_mythos_info = false
		mythos_mob_drops_info = false
		mythos_mob_kills_info = false

	[mythos.qol]
		announce_inqs = true
		better_mythos_event_messages = false
		hide_leg_griffin_error = true

[fishing_pings]
	"toggle:_bronze" = false
	"toggle:_silver" = false
	"toggle:_diamond" = false
	toggle_trophy_fish_messages = false
	"toggle:_gold" = false

	[fishing_pings.crimson_isles]
		vanquisher_ping = false
		radioactive_vial_ping = false
		phlegblast_ping = false
		jawbus_ping = false
		thunder_ping = false

	[fishing_pings.hub_shark]
		meg_pet_drop_ping = false
		great_white_shark_ping = false

	[fishing_pings.hub]
		sea_emperor_ping = false
		squid_pet_drop_ping = false
		dolphin_milestone_pet_drop_ping = false
		carrot_king_ping = false
		lucky_clover_core_ping = false
		water_hydra_ping = false
		guardian_pet_drop_ping = false
		flying_fish_pet_drop_ping = false

	[fishing_pings.winter_island]
		nutcracker_ping = false
		baby_yeti_pet_drop_ping = false
		reindrake_ping = false
		yeti_ping = false

	[fishing_pings.zothers]
		zombie_miner_ping = false
		fawe_default_pings = false

	[fishing_pings.hub_spooky]
		grim_reaper_ping = false
		phantom_fisher_ping = false
		deep_sea_orb_ping = false
		phantom_rod_ping = false
		lucky_hoof_ping = false

["sound/debug"]
	debug_mode = false
	rng_sounds = 0

[dragons]

	[dragons.counter]
		"drag_counter:_trackers" = true
		dragon_counter = true
		"drag_counter:_spawns" = true

	[dragons.qol]
		alert_special_zealot = true
		better_end_messages = true

[misc]
	mute_the_sheep = true

	[misc.spooky]
		trick_or_treat_mobs_ping = true
		primal_fear_ping = false
		hide_fear_messages = false
		primal_fear_main_toggle = false
		headless_horseman_ping = true
		solver_for_karen_fear = false
		primal_fear_spawning_ping = false
		solver_for_mathematician_fear = false
		primal_fear_qol = false

	[misc.end]
		end_protector_ping = false

	[misc.mining]
		bal_pet_drop_alert = false
		lobby_day_counter = false
		scatha_pet_drop_alert = true
		golden_goblin_alert = true

	[misc.jerry]
		hidden_jerry_ping = true

	[misc.dyes]
		dye_pings = true
		announce_dye_pings_in_guild = false

[detections]

	[detections.jawbus]
		"detection:_jawbus" = false

	[detections.vanquisher]
		"detection:_vanquisher" = false

	[detections.thunder]
		"detection:_thunder" = false
		"detection:_vanquisher" = false

