
[timers]
	"king's_scent_timer" = true
	reheated_gummy_bear_timer = true
	phoenix_rekindle_cd_timer = true
	mushy_tonic_timer = true
	spirit_mask_cd_timer = true
	flux_countdown_timer = true

[debug]
	debug_mode = false

[dungeons]
	"toggle:_player_actions" = true
	"toggle:_system_notifications" = true
	"toggle:_interactive_elements" = true
	full_inventory_alert = true
	"toggle:_qol" = true
	"class/cata_lvl_up_ping" = true
	party_finder_message_shortener = true
	melody_terminal_alert = true
	better_dungeon_messages = true
	display_dungeon_blessings = true
	bonzo_mask_cd_timer = true

	[dungeons.secrets]
		"display_secrets_per_run_(per_session)" = true

[sound]
	rng_sounds = 0

["dragons/end"]

	["dragons/end".counter]
		"drag_counter:_trackers" = true
		dragon_counter = true
		dragon_damage_display = true
		"drag_counter:_spawns" = true

	["dragons/end".qol]
		alert_special_zealot = true
		end_protector_ping = true
		better_end_messages = true

[fishing_qol]
	full_thunder_bottle_ping = true

	[fishing_qol.message_hiders]
		hide_sc_messages = true
		hide_blessing_enchant_messages = true
		hide_double_hook_messages = true
		better_fishing_messages = true

	[fishing_qol.timers]
		phoenix_rekindle_cd_timer = true
		mushy_tonic_timer = true
		spirit_mask_cd_timer = true

[counter]
	"counter:_drops" = true
	fishing_counter = true
	"counter:_time_elapsed_since_[rng]" = true
	"counter:_kills" = true
	"counter:_special_funny_counters" = true
	"counter:_mob_since_[rng]" = true
	"counter:_trackers" = true
	"counter:_averages" = true

	[counter.overlay]
		"counter:_drops" = true
		fishing_counter = false
		"counter:_time_elapsed_since_[rng]" = true
		"counter:_kills" = true
		"counter:_special_funny_counters" = true
		"counter:_mob_since_[rng]" = true
		"counter:_trackers" = true
		"counter:_averages" = true

[general_qol]

	[general_qol.messages_qol]
		hide_autopet_messages = true
		removed_watchdog_announcements = true
		hide_soopy_unknown_command_message = true
		grandma_hider = true
		"hide_aote/aotv_message" = true
		hide_snow_cannon_messages = true
		better_stash_messages = true
		hide_click_stash_messages = true
		hide_lightning = false

	[general_qol.commands]
		party_transfer_randomly = true
		auto_warp_command = true
		warpexc_command = true
		auto_notify_new_party_joiners = true
		party_kickoffline_shortcut = true
		party_allinvite_shortcut = true

	[general_qol.qol]
		easy_get_baker_cake = true
		kicked_notifier = true
		boop_notifier = true

[hp_display]
	"display_hp:_phantom_fishers" = true
	mob_hp_display_master_toggle = true
	"display_hp:_vanquishers" = true
	"display_hp:_yeti" = true
	"display_hp:_mythos_mobs" = true
	"display_hp:_grim_reapers" = true
	"display_hp:_jawbus" = true
	"display_hp:_water_hydras" = true
	"display_hp:_inquisitors" = false
	"display_hp:_sea_emperors" = true
	"display_hp:_reindrakes" = true
	"display_hp:_great_whites" = true
	"display_hp:_thunder" = true
	"display_hp:_carrot_kings" = true
	"display_hp:_champions" = false

	[hp_display.toggleables]
		"display_hp:_phantom_fishers" = true
		mob_hp_display_master_toggle = false
		"display_hp:_vanquishers" = true
		"display_hp:_yeti" = true
		"display_hp:_mythos_mobs" = true
		"display_hp:_grim_reapers" = true
		"display_hp:_jawbus" = true
		"display_hp:_water_hydras" = true
		"display_hp:_inquisitors" = true
		"display_hp:_sea_emperors" = true
		"display_hp:_reindrakes" = true
		"display_hp:_great_whites" = true
		"display_hp:_thunder" = true
		"display_hp:_carrot_kings" = true
		"display_hp:_champions" = true

["dragons/end/end"]

	["dragons/end/end".qol]
		end_protector_ping = false

[gui]
	bobber_count = true
	detect_double_jawbus = true
	lobby_day_counter = true
	players_nearby_count = true
	detect_charge_counter = true
	detect_double_thunder = true

	[gui.toggles]
		bobber_count = false
		detect_double_jawbus = false
		players_nearby_count = false
		detect_charge_counter = false
		detect_double_thunder = false

[garden]
	garden_pet_drop_pings = true
	garden_rare_drop_pings = true

	[garden.pest_qol]
		pest_qol = true
		"pest_qol:_screen_pest_alert" = true
		"pest_qol:_auto_set_home_pest" = true
		"pest_qol:_esp" = true
		"pest_qol:_autowarp_pest" = true

	[garden.timers]
		pest_repellent_timer = true
		harbringer_potion_timer = true
		pest_exchange_timer = true

	[garden.overlays]
		vinyl_display = true
		pest_repellent_timer = true
		display_contest_overlay = true
		harbringer_potion_timer = true
		player_yaw_and_pitch = true
		pest_exchange_timer = true
		sprayonator_display = true

	[garden.qol]
		plot_map = true
		pest_qol = true
		sprayonator_no_mat_alert = true
		"pest_qol:_screen_pest_alert" = true
		"pest_qol:_auto_set_home_pest" = true
		"pest_qol:_esp" = true
		"pest_qol:_autowarp_pest" = true
		auto_set_home_pest = true
		hide_sprayonator_expiry_message = true
		screen_pest_alert = true
		sprayonator_selected_mat_message_hider = true
		autowarp_pest = true
		pest_esp = true
		better_garden_messages = true

["sounds/dev"]

	["sounds/dev".debug]
		debug_mode = false

	["sounds/dev".sounds]
		rng_sounds = 4

[mythos]

	[mythos.counter]
		mythos_counter = false
		mythos_mob_averages_info = false
		mythos_mob_trackers_info = false
		general_mythos_info = false
		mythos_mob_drops_info = false
		mythos_mob_kills_info = false

	[mythos.qol]
		announce_inqs = true
		hide_leg_griffin_error = true

[fishing_pings]
	"toggle:_bronze" = false
	"toggle:_silver" = false
	"toggle:_diamond" = false
	toggle_trophy_fish_messages = false
	"toggle:_gold" = false

	[fishing_pings.crimson_isles]
		vanquisher_ping = true
		radioactive_vial_ping = true
		phlegblast_ping = true
		jawbus_ping = true
		thunder_ping = true

	[fishing_pings.hub_shark]
		meg_pet_drop_ping = true
		great_white_shark_ping = true

	[fishing_pings.hub]
		sea_emperor_ping = true
		squid_pet_drop_ping = true
		dolphin_milestone_pet_drop_ping = true
		carrot_king_ping = true
		lucky_clover_core_ping = true
		water_hydra_ping = true
		guardian_pet_drop_ping = true
		flying_fish_pet_drop_ping = true

	[fishing_pings.winter_island]
		nutcracker_ping = true
		baby_yeti_pet_drop_ping = true
		reindrake_ping = true
		yeti_ping = true

	[fishing_pings.zothers]
		zombie_miner_ping = true
		fawe_default_pings = true

	[fishing_pings.hub_spooky]
		grim_reaper_ping = true
		phantom_fisher_ping = true
		deep_sea_orb_ping = true
		phantom_rod_ping = true
		lucky_hoof_ping = true

["sound/debug"]
	debug_mode = false
	rng_sounds = 0

[dragons]

	[dragons.counter]
		"drag_counter:_trackers" = true
		dragon_counter = true
		"drag_counter:_spawns" = true

	[dragons.qol]
		alert_special_zealot = true
		better_end_messages = true

[misc]
	mute_the_sheep = true

	[misc.spooky]
		trick_or_treat_mobs_ping = true
		primal_fear_ping = false
		hide_fear_messages = false
		primal_fear_main_toggle = false
		headless_horseman_ping = true
		solver_for_karen_fear = false
		solver_for_mathematician_fear = false

	[misc.end]
		end_protector_ping = false

	[misc.mining]
		bal_pet_drop_alert = false
		lobby_day_counter = false
		scatha_pet_drop_alert = true
		golden_goblin_alert = true

	[misc.jerry]
		hidden_jerry_ping = true

	[misc.dyes]
		dye_pings = true
		announce_dye_pings_in_guild = false

